# Generated by Django 4.0.1 on 2022-03-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, default='https://s1.1zoom.me/b5050/4/Cats_Kittens_Ginger_484195_3840x2400.jpg', upload_to='photos/%Y/%m/%d', verbose_name='фото'),
        ),
    ]
